### ISSUE TITLE
Spellcheck works when editing but not when creating new cells

### ISSUE THREAD

**Issue by leonsp** [ijmbarr/jupyterlab_spellchecker#1] opened 2018-04-10 18:02 UTC
Thanks for creating this extension!

One issue I've noticed is that spellcheck works when editing Markdown cells, but not when creating a new Markdown cell. Is there a way to expand the functionality to also work when creating new content?

![Screenshot](https://i.imgur.com/KDyxAsq.png)

**Comment by drorata** [comment] 2018-04-11 05:55
I can confirm the issue.

**Comment by ijmbarr** [comment] 2018-04-11 07:13
This issue is due to how the spellchecker applies the overlay mode. 

I'm waiting for [more information](https://github.com/jupyterlab/jupyterlab/issues/4354) about the jupyterlab internals before I can fix it. 

Any suggestions welcome.

**Comment by krassowski** [comment] 2019-07-12 10:24
@leonsp @drorata, this is fixed in the latest release.

**Comment by StevenLi-DS** [comment] 2019-11-04 04:26
Is there any way to fix the misspelled words?

**Closed** 2019-11-04 12:11 UTC

**Comment by leonsp** [comment] 2019-11-04 12:12
@StevenLi-DS It sounds like you may want to open a separate feature request: https://github.com/ijmbarr/jupyterlab_spellchecker/issues/new

I took a quick look and I don't see a way to get suggestions in the current extension.
