### ISSUE TITLE
Update for jupyterlab-0.33.11 ?

### ISSUE THREAD

**Issue by sean-parent** [ijmbarr/jupyterlab_spellchecker#6] opened 2018-08-16 02:20 UTC
Current extension doesn't work with latest jupyterlab.

**Comment by aapeebles** [comment] 2018-08-21 18:31
I second this comment. Any timeline for an update?

**Comment by ijmbarr** [comment] 2018-08-22 06:38
I took a quick look at this: it looks like thing are more complicated than just updating the dependencies. Something in the new release is breaking some of the functionality of this extension. 

It is likely to be a few weeks before I get a chance to dig into what the issue is.

**Comment by ijmbarr** [comment] 2018-09-07 04:58
The issues should be fixed now, up to version 0.34.

**Closed** 2018-12-10 19:05 UTC
